### ISSUE TITLE
pool.on.('after.each') callback cannot be async function

### ISSUE THREAD

**Issue by tka85** [HQarroum/promise-pool#12]
First of all, kudos on a very nice project. Well-designed and well-thought. out

The having been said, I'm facing a roadblock. I see that the callback passed to `pool.on('after.each', callback)` cannot be an async function. Is that by design? Is it possible to support async callbacks for pool events?

**Comment by tka85** [comment]
I see that Node's Eventemitter supports async callbacks: https://stackoverflow.com/questions/47448567/using-async-in-event-emitter.

So it seems it's a design choice. Perhaps there is a better way to do this with the library?

**Comment by HQarroum** [comment]
Hi, and thanks for you message!

Is there any specific reason why you couldn't mark the callback as `async` while using the promise pool events ? The callbacks are called [via a standard emit](https://github.com/HQarroum/promise-pool/blob/master/lib/index.js#L50) and looking at it, it should be possible to mark your callback as `async`.

Halim.

**Comment by tka85** [comment]
Hi @HQarroum 

The mistake was on my side. I thought the problem was I was using an async callback for the `after.each` event. But in reality the problem was that the data passed to the callback contained under `.result` the actual data my pool function had resolved with 

Perhaps worth adding in the docs, that the data returned upon resolution of the function added to the pool for execution, is not what is passed directly to the event handlers. The event handler gets in fact an object where the actual resolved data is under `.result`.

Also if you don't mind me asking, any thoughts on converting this to TypeScript? It's a very nice library and well-worth updating.

I will close this.

**Comment by HQarroum** [comment]
You are right, I should have a closer look for the next version at the result from the callbacks and document better. No current plans for a TypeScript version for now, but I will publish a new major version in the future for sure as I progress with my projects that may include a TypeScript version. But no specific release date in mind :)
